services:
  server:
    container_name: old-age-home-website-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    networks:
      - old-age-home-website
    ports:
      - 3000:3000
    env_file:
      - docker.env

  postgres:
    image: postgres:16
    container_name: old-age-home-website-database
    restart: always
    networks:
      - old-age-home-website
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - docker.env

volumes:
  db_data:

networks:
  old-age-home-website:
    external: true