import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./ui/header";

const mont = Montserrat();


export const metadata: Metadata = {
  title: "Hrudaya Shanthi Old Age Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`w-full h-full ${mont.className} antialiased bg-background-500`}
        >
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
